version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mynetwork1
    volumes:
      - mongo-data:/data/db
  front:
    image: bahachalbia/mern-frontend
    build: 
       context: frontend
       dockerfile: Dockerfile

    container_name: mern-frontend
    ports:
      - 3000:3000
    networks:
      - mynetwork1

  back:
    image: bahachalbia/mern-backend
    build:
       context: backend
       dockerfile: Dockerfile

    container_name: mern-backend
    ports:
       - 5001:5000
    networks:
       - mynetwork1
    depends_on:
       - mongodb
networks:
  mynetwork1:
    driver: bridge
volumes:
 mongo-data:
    driver: local

